### PR TITLE
Release 0.21.16 (982)

### PR DESCRIPTION
**Pull request by Natrinicle**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Fix regex extractor using upstream cherry-picked version change to NewPipeExtractor

#### Fixes the following issue(s)

- Fixes https://github.com/TeamNewPipe/NewPipe/issues/7734

#### Relies on the following changes

- https://github.com/TeamNewPipe/NewPipeExtractor/pull/785

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by connectety** [comment]
Looking at the original commit, the bump of the extractor is missing.
https://github.com/TeamNewPipe/NewPipe/commit/4e633504a82fd9f6c311b658907948130d1a7e6b#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R192

**Comment by Natrinicle** [comment]
> Looking at the original commit, the bump of the extractor is missing. [TeamNewPipe@4e63350#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R192](https://github.com/TeamNewPipe/NewPipe/commit/4e633504a82fd9f6c311b658907948130d1a7e6b#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R192)

Thanks for catching that! I completely missed that the original PR was 2 commits

**Comment by dbenjaminmiller** [comment]
I don't see anything under checks. Can you attach the debug APK to the issue?

**Comment by Natrinicle** [comment]
> I don't see anything under checks. Can you attach the debug APK to the issue?

I didn't build the application, just copied the PR from upstream. The upstream checks are available at: https://github.com/TeamNewPipe/NewPipe/actions/runs/1778307716 and the upstream debug apk is available https://github.com/TeamNewPipe/NewPipe/suites/5135783348/artifacts/154726306.

**Comment by dbenjaminmiller** [comment]
Thanks, got it now!

**Comment by Atemu** [comment]
Please just merge master rather than cherry-picking the commits.

**Comment by Atemu** [comment]
Yup. Though @polymorphicshade will probably just merge master into our master themselves.

**Comment by Coderdude112** [comment]
Any update on this PR @polymorphicshade? This fork is basically useless until https://github.com/TeamNewPipe/NewPipe/issues/7734 is fixed here.

**Comment by HairyMilkshakes** [comment]
> Any update on this PR @polymorphicshade? This fork is basically useless until [TeamNewPipe#7734](https://github.com/TeamNewPipe/NewPipe/issues/7734) is fixed here.

Just patiently wait. I am sure this will be addressed by tomorrow. In the meantime use a browser with uBlock extension :)

**Comment by polymorphicshade** [comment]
Thanks for the pull request, however I much prefer to do the merge/rebasing myself.
Sorry for the delay, I've been dealing with bad health issues these past 2 weeks.

**Comment by fariszr** [comment]
Quick question, the repo shows the last commit is from before 4 days ago, even though the latest newpipe release is only 2 days ago.
Is the source code merge/PR not pushed to github ?

**Comment by Atemu** [comment]
Um yeah, you forgot to push the merge @polymorphicshade... 

\^\^'

**Comment by h4xor666** [comment]
Guys they said they're having health issues, maybe lay off for a bit?

**Comment by fariszr** [comment]
Sure it was just a question.
However this is a license violation of the GPL.

-------- Original Message --------

**Comment by polymorphicshade** [comment]
@Atemu yup I totally forgot to push. I guess that's what happens when I'm doped up on pain meds and having no sleep for 4 days...
@h4xor666 it's ok they are just letting me know. I take no offense.

**Comment by Atemu** [comment]
Oh boy, I hope you recover soon @polymorphicshade!

**Comment by Natrinicle** [comment]
@polymorphicshade Let us know if there's anything we can do to help.

Maintaining a project is not an easy task and I didn't want to come across as demanding which is why I tried to let you know about the upstream patch in as helpful a way as I could think of. If you'd prefer something like a bug report in the issues or some other method please let me know and I'd be happy to modify future requests.

**Pull request closed without merging**
