### PR TITLE
Theme changed 

### LINKED ISSUE #165: Paint it black
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

For the love of (whatever you love), make this thing Black/Gray for Black Theme (Whatever feels aesthetically looks good to you).
See [this](https://github.com/polymorphicshade/NewPipe/issues/165#issuecomment-1077491890).

Screenshot_2022_0323_233416

### Why do you want this feature?

This red bar is annoying AF, and teamnewpipe doesn't wanna do it either.

### Why is the feature relevant to this fork?

It's not, but It's necessary. And you're the last hope who might do it!

### Special Request

If you can't do it with the main, can you at least make another variant with the repainted version, please?

### PR DESCRIPTION
**Pull request by rahaaatul**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)
- [x] UI Improvement

#### Description of the changes in your PR

- Changed NewPipe's ugly dark UI to GitHub's dark UI scheme.

#### Before/After Screenshots/Screen Record

- Before:
Screenshot_20220324162339
Screenshot_20220324162440
Screenshot_20220324162514
Screenshot_20220324162631
Screenshot_20220324162746
Screenshot_20220324163705

- After:
- Color changes in main UI
Screenshot_20220324160748
- Color changes in Search and Playlists
Screenshot_20220324160907
- Color changes in Video Info
Screenshot_20220324161102
- Color changes in download
Screenshot_20220324161249
- Primary/Accent Color Changes for all instances
Screenshot_20220324163006
- Color Changes in settings
Screenshot_20220324163334

#### Fixes the following issue(s)

- Fixes #165 

#### Relies on the following changes

- colors.xml
- colors_services.xml

#### APK testing 

https://github.com/DaPotatoMan/NewPipe/actions/runs/2033484153

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rahaaatul** [comment]
How do I delete Readme.md pull?

**Review by Atemu — CHANGES_REQUESTED** [review]
The GH theme looks great IMO and looks to be well aimplemented and tested.

I do not believe it is a good idea to directly change the theme in a hard-coded manner though. What we need first is a user-accessible way of changing themes and this can be one of the presets (or even default).

Your PR also contains unnecessary changes to the README.

**Comment by Atemu** [comment]
If you meant how to modify your unintended README changes, you start an interactive rebase, select [5365b18](https://github.com/polymorphicshade/NewPipe/pull/167/commits/5365b1817532e58e1bf9eb78a524b5e430e1e1e9) as "edit" instead of "pick", do your changes, stage them, amend the commit, continue the rebase, look at your patch again to make sure you did it right and then force-push.

**Comment by rahaaatul** [comment]
> The GH theme looks great IMO and looks to be well implemented and tested.

• At least it's better that NewPipe's.

> I do not believe it is a good idea to directly change the theme in a hard-coded manner though. What we need first is a user-accessible way of changing themes and this can be one of the presets (or even default).

• Yeah, I think so too. But nobody's doing anything about it after so many requests and creating issues. And me and @DaPotatoMan 's knowledge on java is limited and mine is zero. 

> Your PR also contains unnecessary changes to the README.

• I know that's accidentally happened, I'm new to this stuff.

**Comment by Atemu** [comment]
> At least it's better that NewPipe's.

That's subjective.

> me and @DaPotatoMan 's knowledge on java is limited and mine is zero.

Yeah, not expecting you to do that.

***

FYI, if you want to get rid of the commit with the readme changes, simply remove its line from the interactive rebase.

What you did now is create a new commit that does the reverse of your addition. The old one is still there.

Rebases might sound scary but they're pretty easy when done interactively and you can always escape via `git rebase --abort`.

You'll have to drop the commit and its reversion now though.

**Comment by rahaaatul** [comment]
> Yeah, not expecting you to do that.

Ouch.

Is the latest commit, okay?

**Comment by Atemu** [comment]
Yeah, looks good but I doubt @polymorphicshade would want to change the theme without an option to revert. I certainly wouldn't.

In lieu of theme support, we could make a separate branche with the dark theme. It'd be a minor overhead to merge sponsorblock back into it for every release but that shouldn't be anything big.

What I'm a but unsure about is the legality. Are those colours taken from GH's website source or just approximated? I don't know if a colour scheme constitutes a creative work but I wouldn't be surprised if it does and in that case this would technically be a violation because I don't think their colour scheme is in the public domain. IANAL though.

**Comment by rahaaatul** [comment]
> In lieu of theme support, we could make a separate branche with the dark theme. It'd be a minor overhead to merge sponsorblock back into it for every release but that shouldn't be anything big.

- Is it possible to add themes like Light, Dark, Black? Instead of editing the existing one.
- Can I do that? If so, can you link me to some tutorials?

It'd be cool, if we had multiple options to change theme.


_Theme options in Cloudstream_

> What I'm a but unsure about is the legality. Are those colours taken from GH's website source or just approximated? I don't know if a colour scheme constitutes a creative work but I wouldn't be surprised if it does and in that case this would technically be a violation because I don't think their colour scheme is in the public domain. IANAL though.

I extracted the colors with color picker.

**Comment by cyber199** [comment]
> > At least it's better that NewPipe's.
> 
> That's subjective.

I agree here with the subjectivity.  While its better that it's light theme, I personally find Github's dark theme to be particularly ugly and kinda hard to read, with the default NewPipe theme at least having readability on it's side even if it isn't the prettiest.  More theme presets, or even a full-blown colour configurator would give the best chance for user choice IMHO.

**Comment by polymorphicshade** [comment]
I appreciate the effort put in to this PR, but I'd rather not mess with any theming at the moment. I think this is better suited as a PR for upstream NewPipe.

However I will be referencing this PR when re-branding the app for the future "Tubular" release.

**Pull request closed without merging**
